### PR TITLE
requirements: added dataclasses and removed opencv-python

### PR DESCRIPTION
**Pull request by rohm1**
removed opencv-python (see #1) and added dataclasses.

### CODE REVIEW

**Comment by EhsanKia** [comment]
1. Not sure what you did but the file now shows up as binary and doesn't show diff
2. dataclasses would be useful for 3.6 and below, but I'm actually not sure if the code supports 3.6 to start with, I guess it's fine though, it's not a deal to add it.

**Comment by rohm1** [comment]
1."file requirements.txt" says "Little-endian UTF-16 Unicode text, with CRLF line terminators". not sure if there is a problem with this kind of file on github. a previous commit of yours also displays the file as binary: https://github.com/EhsanKia/CatalogScanner/commit/98b11936eb62cf6d9856520e8876549e83099847#diff-b4ef698db8ca845e5845c4618278f29a
2. I'll have a look tonight, but I needed to install it in order to run the scanner

**Comment by rohm1** [comment]
I have 3.6.9 on ubuntu 18.04, and the scanner ran successfully :)

**Comment by EhsanKia** [comment]
I see, perfect thank you for testing. I'll merge and try to figure out the binary issue separately afterwards.

**Pull request merged**
